<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.4.4.0</Version>
    <Authors>CrystalCast</Authors>
    <PackageProjectUrl>https://github.com/sourpuh/ffxiv_pictomancy</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <Platforms>x64</Platforms>
    <AssemblyName>CrystalCast</AssemblyName>
    <RootNamespace>CrystalCast</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CefSharpBuildAction>Default</CefSharpBuildAction>
    <CefSharpRuntimeIdentifierOverride>win-x64</CefSharpRuntimeIdentifierOverride>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThirdParty\ffxiv_pictomancy\Pictomancy\Pictomancy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" ExcludeAssets="build;buildTransitive;compile;runtime" GeneratePathProperty="true" />
    <PackageReference Include="CefSharp.OffScreen.NETCore" Version="147.0.100" ExcludeAssets="compile" GeneratePathProperty="true" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>$(PkgMicrosoft_Web_WebView2)\lib_manual\netcoreapp3.0\Microsoft.Web.WebView2.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Content Include="$(PkgMicrosoft_Web_WebView2)\runtimes\win-x64\native\WebView2Loader.dll">
      <Link>WebView2Loader.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>
